[build]
  command = "npm run build"
  publish = "dist"               # or "build" if CRA

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[dev]
  command = "npm run dev"        # starts Vite
  targetPort = 8080              # your Vite port
  port = 8888                    # Netlify proxy (open http://localhost:8888)

# Pretty API path for both dev & prod
[[redirects]]
  from = "/api/create-order"
  to = "/.netlify/functions/create-order"
  status = 200
